name: End-to-end tests ðŸ§ª
on: push
jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
  cypress-run-firefox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
  cypress-run-edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: edge
  cypress-run-safari:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install webkit dependencies for Linux
        run: npx playwright install-deps webkit
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --browser webkit
